export const Employees = [
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.j@yopmail.com",
    phoneNumber: "+1-202-555-0111",
    dateOfBirth: "1995-03-15",
    gender: "Female",
    employmentStartDate: "2010-06-01",
    employmentType: "Permanent",
    designationId: "Managerial",
    departmentId: "Engineering",
    companyRole: "Engineering Manager"
  },
  {
    firstName: "Brian",
    lastName: "Smith",
    email: "brian.s@yopmail.com",
    phoneNumber: "+1-202-555-0122",
    dateOfBirth: "1990-08-22",
    gender: "Male",
    employmentStartDate: "2008-09-15",
    employmentType: "Permanent",
    designationId: "Executive",
    departmentId: "Product",
    companyRole: "Product Director"
  },
  {
    firstName: "Carla",
    lastName: "Miller",
    email: "carla.m@yopmail.com",
    phoneNumber: "+1-202-555-0133",
    dateOfBirth: "1998-12-05",
    gender: "Female",
    employmentStartDate: "2018-01-10",
    employmentType: "Permanent",
    designationId: "Mid",
    departmentId: "Engineering",
    companyRole: "Software Engineer"
  },
  {
    firstName: "David",
    lastName: "Brown",
    email: "david.b@yopmail.com",
    phoneNumber: "+1-202-555-0144",
    dateOfBirth: "1992-07-19",
    gender: "Male",
    employmentStartDate: "2012-03-22",
    employmentType: "Permanent",
    designationId: "Senior",
    departmentId: "Engineering",
    companyRole: "Senior Software Engineer"
  },
  {
    firstName: "Eva",
    lastName: "Davis",
    email: "eva.d@yopmail.com",
    phoneNumber: "+1-202-555-0155",
    dateOfBirth: "1996-11-30",
    gender: "Female",
    employmentStartDate: "2015-07-01",
    employmentType: "Permanent",
    designationId: "Mid",
    departmentId: "Design",
    companyRole: "UI/UX Designer"
  },
  {
    firstName: "Frank",
    lastName: "Wilson",
    email: "frank.w@yopmail.com",
    phoneNumber: "+1-202-555-0166",
    dateOfBirth: "1988-05-14",
    gender: "Male",
    employmentStartDate: "2006-10-12",
    employmentType: "Permanent",
    designationId: "Executive",
    departmentId: "HR",
    companyRole: "HR Director"
  },
  {
    firstName: "Grace",
    lastName: "Lee",
    email: "grace.l@yopmail.com",
    phoneNumber: "+1-202-555-0177",
    dateOfBirth: "1999-02-20",
    gender: "Female",
    employmentStartDate: "2021-03-15",
    employmentType: "Contract",
    designationId: "Junior",
    departmentId: "Engineering",
    companyRole: "Junior Developer"
  },
  {
    firstName: "Henry",
    lastName: "Taylor",
    email: "henry.t@yopmail.com",
    phoneNumber: "+1-202-555-0188",
    dateOfBirth: "1991-09-07",
    gender: "Male",
    employmentStartDate: "2010-05-01",
    employmentType: "Permanent",
    designationId: "Senior",
    departmentId: "Engineering",
    companyRole: "Team Lead"
  },
  {
    firstName: "Isabella",
    lastName: "Anderson",
    email: "isabella.a@yopmail.com",
    phoneNumber: "+1-202-555-0199",
    dateOfBirth: "1997-01-18",
    gender: "Female",
    employmentStartDate: "2017-08-20",
    employmentType: "Permanent",
    designationId: "Mid",
    departmentId: "Marketing",
    companyRole: "Marketing Specialist"
  },
  {
    firstName: "Jack",
    lastName: "Thomas",
    email: "jack.t@yopmail.com",
    phoneNumber: "+1-202-555-0200",
    dateOfBirth: "1993-06-11",
    gender: "Male",
    employmentStartDate: "2014-02-15",
    employmentType: "Permanent",
    designationId: "Senior",
    departmentId: "Product",
    companyRole: "Product Manager"
  },
  {
    firstName: "Karen",
    lastName: "Martinez",
    email: "karen.m@yopmail.com",
    phoneNumber: "+1-202-555-0211",
    dateOfBirth: "1995-10-25",
    gender: "Female",
    employmentStartDate: "2018-11-05",
    employmentType: "Contract",
    designationId: "Junior",
    departmentId: "Design",
    companyRole: "Graphic Designer"
  },
  {
    firstName: "Leo",
    lastName: "Harris",
    email: "leo.h@yopmail.com",
    phoneNumber: "+1-202-555-0222",
    dateOfBirth: "1990-12-02",
    gender: "Male",
    employmentStartDate: "2009-06-18",
    employmentType: "Permanent",
    designationId: "Executive",
    departmentId: "Finance",
    companyRole: "Finance Director"
  },
  {
    firstName: "Mia",
    lastName: "Clark",
    email: "mia.c@yopmail.com",
    phoneNumber: "+1-202-555-0233",
    dateOfBirth: "1998-04-16",
    gender: "Female",
    employmentStartDate: "2019-09-01",
    employmentType: "Permanent",
    designationId: "Mid",
    departmentId: "Engineering",
    companyRole: "Software Engineer"
  },
  {
    firstName: "Nathan",
    lastName: "Lewis",
    email: "nathan.l@yopmail.com",
    phoneNumber: "+1-202-555-0244",
    dateOfBirth: "1992-08-30",
    gender: "Male",
    employmentStartDate: "2011-04-22",
    employmentType: "Permanent",
    designationId: "Senior",
    departmentId: "Engineering",
    companyRole: "Senior Developer"
  },
  {
    firstName: "Olivia",
    lastName: "Walker",
    email: "olivia.w@yopmail.com",
    phoneNumber: "+1-202-555-0255",
    dateOfBirth: "1996-05-12",
    gender: "Female",
    employmentStartDate: "2016-07-10",
    employmentType: "Permanent",
    designationId: "Mid",
    departmentId: "Product",
    companyRole: "Product Analyst"
  },
  {
    firstName: "Paul",
    lastName: "Robinson",
    email: "paul.r@yopmail.com",
    phoneNumber: "+1-202-555-0266",
    dateOfBirth: "1989-03-28",
    gender: "Male",
    employmentStartDate: "2007-05-14",
    employmentType: "Permanent",
    designationId: "Executive",
    departmentId: "Engineering",
    companyRole: "CTO"
  },
  {
    firstName: "Quinn",
    lastName: "Perez",
    email: "quinn.p@yopmail.com",
    phoneNumber: "+1-202-555-0277",
    dateOfBirth: "1997-11-03",
    gender: "Female",
    employmentStartDate: "2020-01-05",
    employmentType: "Contract",
    designationId: "Junior",
    departmentId: "Marketing",
    companyRole: "Marketing Associate"
  },
  {
    firstName: "Ryan",
    lastName: "Hall",
    email: "ryan.h@yopmail.com",
    phoneNumber: "+1-202-555-0288",
    dateOfBirth: "1994-09-15",
    gender: "Male",
    employmentStartDate: "2013-03-01",
    employmentType: "Permanent",
    designationId: "Senior",
    departmentId: "Engineering",
    companyRole: "DevOps Engineer"
  },
  {
    firstName: "Sophia",
    lastName: "Young",
    email: "sophia.y@yopmail.com",
    phoneNumber: "+1-202-555-0299",
    dateOfBirth: "1998-07-20",
    gender: "Female",
    employmentStartDate: "2021-08-12",
    employmentType: "Contract",
    designationId: "Junior",
    departmentId: "Design",
    companyRole: "Junior Designer"
  },
  {
    firstName: "Thomas",
    lastName: "King",
    email: "thomas.k@yopmail.com",
    phoneNumber: "+1-202-555-0300",
    dateOfBirth: "1991-01-11",
    gender: "Male",
    employmentStartDate: "2010-12-20",
    employmentType: "Permanent",
    designationId: "Managerial",
    departmentId: "Product",
    companyRole: "Product Manager"
  }
];
